"""target_replica_only_flag

Revision ID: a15613e25129
Revises:     3bfc211405ff
Create Date: 2026-04-18 03:52:33.118213+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- may reference sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic
revision: str = 'a15613e25129'
down_revision: str | Sequence[str] | None = '3bfc211405ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add as nullable so existing rows accept the change, set False for
    # all existing rows (production-safe default), then enforce NOT NULL.
    op.add_column(
        'targets',
        sa.Column('replica_only', sa.Boolean(), nullable=True,
                  server_default=sa.false()),
    )
    op.execute("UPDATE targets SET replica_only = false WHERE replica_only IS NULL")
    op.alter_column('targets', 'replica_only', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'replica_only')
    # ### end Alembic commands ###
