"""fact_dedup_constraint

Revision ID: 3bfc211405ff
Revises:     83d0090e0d63
Create Date: 2026-04-18 03:19:16.785015+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- may reference sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic
revision: str = '3bfc211405ff'
down_revision: str | Sequence[str] | None = '83d0090e0d63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facts_fingerprint'), table_name='facts')
    op.create_unique_constraint('uq_facts_scan_fingerprint', 'facts', ['scan_id', 'fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_facts_scan_fingerprint', 'facts', type_='unique')
    op.create_index(op.f('ix_facts_fingerprint'), 'facts', ['fingerprint'], unique=False)
    # ### end Alembic commands ###
