"""finding_triage_notes

Revision ID: b366c4ba184a
Revises:     a15613e25129
Create Date: 2026-04-18 04:13:10.578838+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- may reference sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic
revision: str = 'b366c4ba184a'
down_revision: str | Sequence[str] | None = 'a15613e25129'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('triage_notes', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=False))
    op.alter_column('targets', 'replica_only',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('targets', 'replica_only',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('findings', 'triage_notes')
    # ### end Alembic commands ###
