"""initial_schema_phase1

Revision ID: 83d0090e0d63
Revises:     
Create Date: 2026-04-17 16:48:02.440888+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  -- autogenerated AutoString references
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision: str = '83d0090e0d63'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_cpe',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cpe23', sa.String(length=256), nullable=False),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.PrimaryKeyConstraint('cpe23')
    )
    op.create_index(op.f('ix_kb_cpe_created_at'), 'kb_cpe', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_cpe_product'), 'kb_cpe', ['product'], unique=False)
    op.create_index(op.f('ix_kb_cpe_vendor'), 'kb_cpe', ['vendor'], unique=False)
    op.create_table('kb_cve',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('published', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('last_modified', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cvss_vector', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('cpes', sa.ARRAY(sa.String(length=256)), server_default='{}', nullable=False),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_index('ix_kb_cve_cpes', 'kb_cve', ['cpes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_kb_cve_created_at'), 'kb_cve', ['created_at'], unique=False)
    op.create_index('ix_kb_cve_severity', 'kb_cve', ['severity'], unique=False)
    op.create_table('kb_nuclei_templates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('template_id', sa.String(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('cves', sa.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_kb_nuclei_templates_created_at'), 'kb_nuclei_templates', ['created_at'], unique=False)
    op.create_index('ix_nuclei_severity', 'kb_nuclei_templates', ['severity'], unique=False)
    op.create_index('ix_nuclei_tags', 'kb_nuclei_templates', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('persona_definitions',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('rate_limit_rps', sa.Integer(), nullable=False),
    sa.Column('allowed_phases', sa.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('scoped_target_tags', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_persona_name')
    )
    op.create_index(op.f('ix_persona_definitions_created_at'), 'persona_definitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_persona_definitions_name'), 'persona_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_persona_definitions_ulid'), 'persona_definitions', ['ulid'], unique=True)
    op.create_table('rules',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('personas', sa.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('source_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('priority >= 0 AND priority <= 1000', name='ck_rules_priority'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version', name='uq_rules_id_version')
    )
    op.create_index('ix_rules_body', 'rules', ['body'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_rules_created_at'), 'rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_rules_enabled'), 'rules', ['enabled'], unique=False)
    op.create_index('ix_rules_phase', 'rules', ['phase'], unique=False)
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rules_ulid'), 'rules', ['ulid'], unique=True)
    op.create_table('targets',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('cidrs', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('domains', sa.ARRAY(sa.String(length=253)), server_default='{}', nullable=False),
    sa.Column('allowed_personas', sa.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=8192), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_targets_slug')
    )
    op.create_index(op.f('ix_targets_created_at'), 'targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_targets_slug'), 'targets', ['slug'], unique=False)
    op.create_index('ix_targets_tags', 'targets', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_targets_ulid'), 'targets', ['ulid'], unique=True)
    op.create_table('scans',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('task_queue', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('started_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('executions_total', sa.Integer(), nullable=False),
    sa.Column('facts_total', sa.Integer(), nullable=False),
    sa.Column('findings_total', sa.Integer(), nullable=False),
    sa.Column('terminal_reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_persona'), 'scans', ['persona'], unique=False)
    op.create_index(op.f('ix_scans_state'), 'scans', ['state'], unique=False)
    op.create_index(op.f('ix_scans_target_id'), 'scans', ['target_id'], unique=False)
    op.create_index('ix_scans_target_state', 'scans', ['target_id', 'state'], unique=False)
    op.create_index(op.f('ix_scans_ulid'), 'scans', ['ulid'], unique=True)
    op.create_index('ix_scans_workflow_id', 'scans', ['workflow_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('persona', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'sequence', name='uq_audit_scan_sequence')
    )
    op.create_index('ix_audit_event', 'audit_log', ['event'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_ulid'), 'audit_log', ['ulid'], unique=True)
    op.create_index('ix_audit_scan_event', 'audit_log', ['scan_id', 'event'], unique=False)
    op.create_table('drift_snapshots',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('host_count', sa.Integer(), nullable=False),
    sa.Column('open_port_count', sa.Integer(), nullable=False),
    sa.Column('finding_counts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('fact_fingerprints', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_index(op.f('ix_drift_snapshots_created_at'), 'drift_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_drift_snapshots_target_id'), 'drift_snapshots', ['target_id'], unique=False)
    op.create_index(op.f('ix_drift_snapshots_ulid'), 'drift_snapshots', ['ulid'], unique=True)
    op.create_index('ix_drift_target_time', 'drift_snapshots', ['target_id', 'created_at'], unique=False)
    op.create_table('executions',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('argv', sa.ARRAY(sa.String(length=2048)), server_default='{}', nullable=False),
    sa.Column('env_redacted', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('container_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('rejected_reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stdout_bytes', sa.Integer(), nullable=False),
    sa.Column('stderr_bytes', sa.Integer(), nullable=False),
    sa.Column('artifact_meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('stdout_head', sa.Text(), nullable=True),
    sa.Column('stderr_head', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_container_id', 'executions', ['container_id'], unique=False)
    op.create_index(op.f('ix_executions_created_at'), 'executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_executions_rule_id'), 'executions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_executions_scan_id'), 'executions', ['scan_id'], unique=False)
    op.create_index('ix_executions_scan_state', 'executions', ['scan_id', 'state'], unique=False)
    op.create_index(op.f('ix_executions_state'), 'executions', ['state'], unique=False)
    op.create_index('ix_executions_tool', 'executions', ['tool'], unique=False)
    op.create_index(op.f('ix_executions_ulid'), 'executions', ['ulid'], unique=True)
    op.create_table('findings',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=8192), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cvss_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('cve_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('affected', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('remediation', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('triaged_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.CheckConstraint('cvss_score >= 0 AND cvss_score <= 10', name='ck_findings_cvss'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    op.create_index('ix_findings_cve', 'findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index('ix_findings_scan_severity', 'findings', ['scan_id', 'severity'], unique=False)
    op.create_index(op.f('ix_findings_ulid'), 'findings', ['ulid'], unique=True)
    op.create_table('drift_deltas',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('from_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('to_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('added_fingerprints', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('removed_fingerprints', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('severity_shift', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['from_snapshot_id'], ['drift_snapshots.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['to_snapshot_id'], ['drift_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_deltas_created_at'), 'drift_deltas', ['created_at'], unique=False)
    op.create_index('ix_drift_deltas_target', 'drift_deltas', ['target_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_drift_deltas_target_id'), 'drift_deltas', ['target_id'], unique=False)
    op.create_index(op.f('ix_drift_deltas_ulid'), 'drift_deltas', ['ulid'], unique=True)
    op.create_table('facts',
    sa.Column('ulid', sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('fact_type', sa.String(length=32), nullable=False),
    sa.Column('source_tool', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_body', 'facts', ['body'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_facts_created_at'), 'facts', ['created_at'], unique=False)
    op.create_index(op.f('ix_facts_fact_type'), 'facts', ['fact_type'], unique=False)
    op.create_index('ix_facts_fingerprint', 'facts', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_facts_scan_id'), 'facts', ['scan_id'], unique=False)
    op.create_index('ix_facts_scan_type', 'facts', ['scan_id', 'fact_type'], unique=False)
    op.create_index(op.f('ix_facts_ulid'), 'facts', ['ulid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facts_ulid'), table_name='facts')
    op.drop_index('ix_facts_scan_type', table_name='facts')
    op.drop_index(op.f('ix_facts_scan_id'), table_name='facts')
    op.drop_index('ix_facts_fingerprint', table_name='facts')
    op.drop_index(op.f('ix_facts_fact_type'), table_name='facts')
    op.drop_index(op.f('ix_facts_created_at'), table_name='facts')
    op.drop_index('ix_facts_body', table_name='facts', postgresql_using='gin')
    op.drop_table('facts')
    op.drop_index(op.f('ix_drift_deltas_ulid'), table_name='drift_deltas')
    op.drop_index(op.f('ix_drift_deltas_target_id'), table_name='drift_deltas')
    op.drop_index('ix_drift_deltas_target', table_name='drift_deltas')
    op.drop_index(op.f('ix_drift_deltas_created_at'), table_name='drift_deltas')
    op.drop_table('drift_deltas')
    op.drop_index(op.f('ix_findings_ulid'), table_name='findings')
    op.drop_index('ix_findings_scan_severity', table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_index('ix_findings_cve', table_name='findings')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_executions_ulid'), table_name='executions')
    op.drop_index('ix_executions_tool', table_name='executions')
    op.drop_index(op.f('ix_executions_state'), table_name='executions')
    op.drop_index('ix_executions_scan_state', table_name='executions')
    op.drop_index(op.f('ix_executions_scan_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_rule_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_created_at'), table_name='executions')
    op.drop_index('ix_executions_container_id', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_drift_target_time', table_name='drift_snapshots')
    op.drop_index(op.f('ix_drift_snapshots_ulid'), table_name='drift_snapshots')
    op.drop_index(op.f('ix_drift_snapshots_target_id'), table_name='drift_snapshots')
    op.drop_index(op.f('ix_drift_snapshots_created_at'), table_name='drift_snapshots')
    op.drop_table('drift_snapshots')
    op.drop_index('ix_audit_scan_event', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ulid'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index('ix_audit_event', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_scans_workflow_id', table_name='scans')
    op.drop_index(op.f('ix_scans_ulid'), table_name='scans')
    op.drop_index('ix_scans_target_state', table_name='scans')
    op.drop_index(op.f('ix_scans_target_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_state'), table_name='scans')
    op.drop_index(op.f('ix_scans_persona'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_targets_ulid'), table_name='targets')
    op.drop_index('ix_targets_tags', table_name='targets', postgresql_using='gin')
    op.drop_index(op.f('ix_targets_slug'), table_name='targets')
    op.drop_index(op.f('ix_targets_created_at'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_rules_ulid'), table_name='rules')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_index('ix_rules_phase', table_name='rules')
    op.drop_index(op.f('ix_rules_enabled'), table_name='rules')
    op.drop_index(op.f('ix_rules_created_at'), table_name='rules')
    op.drop_index('ix_rules_body', table_name='rules', postgresql_using='gin')
    op.drop_table('rules')
    op.drop_index(op.f('ix_persona_definitions_ulid'), table_name='persona_definitions')
    op.drop_index(op.f('ix_persona_definitions_name'), table_name='persona_definitions')
    op.drop_index(op.f('ix_persona_definitions_created_at'), table_name='persona_definitions')
    op.drop_table('persona_definitions')
    op.drop_index('ix_nuclei_tags', table_name='kb_nuclei_templates', postgresql_using='gin')
    op.drop_index('ix_nuclei_severity', table_name='kb_nuclei_templates')
    op.drop_index(op.f('ix_kb_nuclei_templates_created_at'), table_name='kb_nuclei_templates')
    op.drop_table('kb_nuclei_templates')
    op.drop_index('ix_kb_cve_severity', table_name='kb_cve')
    op.drop_index(op.f('ix_kb_cve_created_at'), table_name='kb_cve')
    op.drop_index('ix_kb_cve_cpes', table_name='kb_cve', postgresql_using='gin')
    op.drop_table('kb_cve')
    op.drop_index(op.f('ix_kb_cpe_vendor'), table_name='kb_cpe')
    op.drop_index(op.f('ix_kb_cpe_product'), table_name='kb_cpe')
    op.drop_index(op.f('ix_kb_cpe_created_at'), table_name='kb_cpe')
    op.drop_table('kb_cpe')
    # ### end Alembic commands ###
